### ISSUE TITLE
Unable to share pictures via public proxy

### ISSUE THREAD

**Issue by rufflestomp** [alangrainger/immich-public-proxy#12]
Hello!

I'm having an issue where I can't view an immich share via the immich-public-proxy. The share works using the immich/share url, but the public proxy times out (eventually my nginx reverse proxy throws an error 504). Both immich and immich-public-proxy are hosted via docker (on ports 2283 and 2284 respectively), and are both behind an nginx reverse proxy for access over the internet. If it matters, they are not in the same docker-compose file.

When navigating just to the public proxy url (hosted at photoshare.x.com), I get a blank page, along with the immich icon on the tab, so I'm guessing that _something_ is working? I'd appreciate some help getting this set up!

**Comment by alangrainger** [comment]
What message(s) do you get in the console / stdout of the docker container?

**Comment by rufflestomp** [comment]
This is what I see:
'
immich-public-proxy  | 2024-11-10T17:01:56: PM2 log: Launching in no daemon mode
immich-public-proxy  | 2024-11-10T17:01:56: PM2 log: App [index:0] starting in -fork mode-
immich-public-proxy  | 2024-11-10T17:01:56: PM2 log: App [index:0] online
immich-public-proxy  | 2024-11-10T17:01:56+00:00 Server started
immich-public-proxy  | 2024-11-10T17:02:02+00:00 Invalid route /
immich-public-proxy  | TypeError: fetch failed
immich-public-proxy  |     at node:internal/deps/undici/undici:13392:13
immich-public-proxy  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
immich-public-proxy  |   [cause]: Error: connect ECONNREFUSED 127.0.0.1:2283
immich-public-proxy  |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1610:16) {
immich-public-proxy  |     errno: -111,
immich-public-proxy  |     code: 'ECONNREFUSED',
immich-public-proxy  |     syscall: 'connect',
immich-public-proxy  |     address: '127.0.0.1',
immich-public-proxy  |     port: 2283
immich-public-proxy  |   }
immich-public-proxy  | }
`

Is there maybe an immich setting I'm missing?

**Comment by alangrainger** [comment]
```
connect ECONNREFUSED 127.0.0.1:2283
```

Try accessing Immich with your local server IP, not the localhost IP.

**Comment by rufflestomp** [comment]
That was it, thank you!
Clearly I have a bunch to learn about docker!
