### ISSUE TITLE
How do I use this with Tailscale / Taefik?

### ISSUE THREAD

**Issue by wrapper** [alangrainger/immich-public-proxy#13]
Hey

My current setup is based on this: https://github.com/AdrienPoupa/docker-compose-nas

In short it is behind taefik and tailscale to allow me to access immich from the VPN only. I would still like to be able to make custom shares that I can make public.

Do I need to map a (sub)domain to my local public IP to get the public proxy to work? Forgive my ignorance here!

**Comment by alangrainger** [comment]
> Do I need to map a (sub)domain to my local public IP to get the public proxy to work?

That is exactly correct.

> Forgive my ignorance here!

Unfortunately I've never used Traefik, so I am equally ignorant in terms of Traefik-specific advice. But you would need to have Traefik serve the requests to IPP _without_ going through Tailscale.

**Comment by alangrainger** [comment]
I'll close this as it isn't a bug, but feel free to keep replying and I'll assist where I can.
