### ISSUE TITLE
Upload?

### ISSUE THREAD

**Issue by valon0388** [alangrainger/immich-public-proxy#18]
Just want to confirm something. There's no way that you could add an option to upload photos while keeping the project as lean as you're looking to. Right?

Great work, btw. Not trying to say this isn't incredibly useful. I think I just have a use case that's outside the scope of this project.

**Comment by alangrainger** [comment]
Sorry, but no that's not something which will be added for this project.

In this case it's not about keeping the project lean, it's about risk. I won't be adding any features which require Write access to Immich, as the purpose of this project is to abstract away from any risk to your Immich instance.

**Comment by ecker00** [comment]
I think this would be an important addition (but maybe as a **fork**).

Currently it's a social risk of _how_ other people share images back to us. Having this feature would pose less risk for many than personal pictures being put on random services.

**Comment by alangrainger** [comment]
@ecker00 why wouldn't you simply use Immich for that? If you're concerned about Immich's own authentication, you could put it behind [Authentik](https://github.com/goauthentik/authentik) or similar as a double layer of security.

**Comment by ecker00** [comment]
That is a very good suggestion, thank you. 👍
