### ISSUE TITLE
Password protected share returns garbled web page

### ISSUE THREAD

**Issue by zejar** [alangrainger/immich-public-proxy#20]
Hi!
I'm having an issue with password protected shares. After sharing an image/album without a password set it works as expected.
However, after sharing an image/album with password protection set, a garbled web page is returned (after entering the password into the password prompt). See attached image.

Output from Immich public proxy logs: `2024-11-14T10:03:29+00:00 Serving link nXyuB4fkxaH-<etcetera>`.

This issue occurs both with a reverse proxy in front of Immich public proxy and without a reverse proxy (visiting docker host IP:3000 directly). The `config.json` file is left as default, removing the mapping for a custom `config.json` in the compose file doesn't alter the behaviour and neither does disabling all plugins in the webbrowser.

Garbled webpage after entering the password: <img width="1512" alt="Screenshot 2024-11-14 at 11 05 14" src="https://github.com/user-attachments/assets/4f6bbb02-82c2-417d-b257-41db699b3e4d">

**Comment by alangrainger** [comment]
Thanks - I can see that this is an issue only if you share a single image. I will get that fixed.

You can test an album using this link, password is `test`

https://immich-demo.note.sx/share/-T5vDMUGeNzUQBHrrlNxR3cuqlLcrcJRmd0TVAJl5DRjekkZiZ_AqCrs3dUm13Y3WjI

**Comment by alangrainger** [comment]
Thanks - this is now resolved in v1.4.2
