### ISSUE TITLE
mobileSettings in config.json settings not applied

### ISSUE THREAD

**Issue by jimeelicious** [alangrainger/immich-public-proxy#21]
Variation of Issue #9

Seems like the mobile responsive version does not honor the "showCloseIcon" and "download" attributes under mobileSettings within config.json 

{
  "lightGallery": {
    "controls": true,
    "download": true,
    "mobileSettings": {
      "controls": false,
      **"showCloseIcon": true,
      "download": true**
    }
  }
}

![image](https://github.com/user-attachments/assets/148a2285-c230-400b-bdcb-613650caa39c)

Noticed this issue starting from v1.3.6 up to the current version 1.4.2. Desktop/full view seems to be fine, though.

**Comment by alangrainger** [comment]
What do you mean by "does not honor"? In your JSON you have both set to true, and in the screenshot you have both showing, which is exactly what you would and should expect.

**Comment by jimeelicious** [comment]
Whoops, I used the wrong screenshot, and the intended photo was supposed to show these icons not appearing in the mobile responsive view. Sorry about that.

**Comment by alangrainger** [comment]
Check your page source to see what the lightGallery configuration is in the HTML. 

You potentially have the old config cached in Cloudflare or whatever cache you're using.

I can confirm there is no issue if you set your config like this:

```
{
  "ipp": {
    "responseHeaders": {
      "Cache-Control": "public, max-age=2592000"
    },
    "singleImageGallery": false,
    "singleItemAutoOpen": true,
    "downloadOriginalPhoto": true
  },
  "lightGallery": {
    "controls": true,
    "download": true,
    "mobileSettings": {
      "controls": false,
      "showCloseIcon": false,
      "download": false
    }
  }
}
```

Here's the result on mobile:

![image](https://github.com/user-attachments/assets/4e25bef6-1886-4c99-a94b-99b9dd81bba2)

**Comment by alangrainger** [comment]
I noticed you said "mobile responsive" view. If you're testing this from desktop browser, make sure you refresh the page after resizing the browser to mobile size........

**Comment by jimeelicious** [comment]
Can you confirm on your end, if setting showCloseIcon and download set to true, the changes reflect?

I temporarily disabled caching on Cloudflare, tried setting the browser size to a mobile size and refreshed the page as mentioned in an incognito window. 

![image](https://github.com/user-attachments/assets/b2159b59-6c48-4a93-9264-4dcbd397c944)
![image](https://github.com/user-attachments/assets/59ce8b48-b0af-4825-ba36-6af7197a3c95)

config.json settings:
```
{
   "ipp": {
       "responseHeaders": {
           "Cache-Control": "public, max-age=2592000"
       },
       "singleImageGallery": false,
       "singleItemAutoOpen": true
       "downloadOriginalPhoto": true
   },
{
  "lightGallery": {
    "controls": true,
    "download": true,
    "mobileSettings": {
      "controls": false,
      "showCloseIcon": true,
      "download": true,
    }
  }
}
```

**Comment by alangrainger** [comment]
> Can you confirm on your end, if setting showCloseIcon and download set to true, the changes reflect?

You need to set them to `false` - as in "Do not show" = false.

**Comment by jimeelicious** [comment]
Sorry if I was not clear, the intended behavior is to display the icons, hence the config.json set to true. 

But in the screenshot, the icons do not appear despite true being set in the json.

**Comment by alangrainger** [comment]
You literally have them showing here:

![image](https://github.com/user-attachments/assets/643be888-a5d8-4e4a-a203-f4b6b07ed205)

:sob: I am so confused!

And you can test it here in the demo gallery - they both show:

https://immich-demo.note.sx/share/ffSw63qnIYMtpmg0RNvOui0Dpio7BbxsObjvH8YZaobIjIAzl5n7zTX5d6EDHdOYEvo

![image](https://github.com/user-attachments/assets/3c15a369-8253-4c39-81f9-a3e14196d808)

I have no idea what is going on in this ticket....

**Comment by jimeelicious** [comment]
Haha my apologies! At the time of the ticket creation, I had used the the wrong screenshot. Shame on me for copying and pasting and not being careful and the initial post screenshot should have shown the icons _not_ showing despite the json config settings for them set to true. (original post corrected just now)

Thanks for confirming that everything is okay on the demo ticket. Once I'm able to get to my server later today or tomorrow I can do some debugging as it seems to be narrowed on something on my end. Always appreciate your work, help, and promptness replying!
