### ISSUE TITLE
404 trying to access page

### ISSUE THREAD

**Issue by rossdargan** [alangrainger/immich-public-proxy#22]
I have immich on one vlan (192.168.10.121) 
immich proxy on another (192.168.99.20)

Immich proxy is itself proxied via NPM (192.168.99.99)

which is exposed via a cloud flare tunnel (https://immich.mydomain.com)

When I hit the external DNS name I can see this in the log

https://immich.mydomain.uk/share/ah8***

```immich-public-proxy  | 2024-11-15T16:05:18+00:00 Immich response 200 for key ah8r***`

So I know it's hitting the proxy, and the proxy can comminate with immich, but my browser shows exactly the same (and I get another row in the logs:

http://192.168.99.20:3000/share/ah8***

if I hit immich directly the share works. 

If I use wget inside the container I get this:

![image](https://github.com/user-attachments/assets/676190f6-fe1c-48a8-b931-b8acf9107e35)
so I know it can connect.

I'm not really sure why this isn't working. I think it should be pretty straightforward!

**Comment by alangrainger** [comment]
Assuming immich.mydomain.com is the domain for Immich Public Proxy, what do you get if you visit the healthcheck URL?

https://immich.mydomain.com/healthcheck

**Comment by alangrainger** [comment]
Interesting - it looks like Immich is returning an unexpected non -JSON response for that link.

I have updated in v1.4.4 to output additional debug logging in this circumstance.

Can you please pull the new 1.4.4 version and let me know what is the new output following this:

```
immich-public-proxy | 2024-11-15T16:05:18+00:00 Immich response 200 for key ah8r***
```

**Comment by rossdargan** [comment]
Thanks for your super quick reply!

here are the logs:

2024-11-15T17:22:08+00:00 Immich response 200 for key **_UADJMBU
<!doctype html>
<html>
  <head>
    
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png" />
    <link rel="icon" type="image/png" sizes="48x48" href="/favicon-48.png" />

**Comment by rossdargan** [comment]
2024-11-15T17:22:08+00:00 Immich response 200 for key*
<!doctype html>
<html>
  <head>
    
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png" />
    <link rel="icon" type="image/png" sizes="48x48" href="/favicon-48.png" />

**Comment by alangrainger** [comment]
Seems like IPP is unable to reach the Immich API path. You'll have to do some digging at your end. 

What do you get when accessing this Immich API URL, making sure to use the exact same address IPP is configured to use: 

`http://192.168.10.121/api/server/ping'

**Comment by rossdargan** [comment]
The wash was the Immich server url had a trailing /! 

Thank you for the support and fab project!

**Comment by alangrainger** [comment]
Thanks, good catch - I've update the code to remove a trailing slash if there is one.
