### ISSUE TITLE
Download All doesn't work for password-protected links

### ISSUE THREAD

**Issue by alangrainger** [alangrainger/immich-public-proxy#29]
Reported here: https://github.com/alangrainger/immich-public-proxy/issues/25#issuecomment-2485369931

Known issue, will need to do a bit of refactoring.

**Comment by Frikk** [comment]
I also experience this issue. I only share password protected links and like to have the download all option available. Thank you for the otherwise great focused app :)

**Comment by alangrainger** [comment]
Fixed in v1.5.3
