### ISSUE TITLE
Single file moint not possible - change to folder mount

### ISSUE THREAD

**Issue by DrakeHamString** [alangrainger/immich-public-proxy#33]
Hi there, 
in your documentation you described how to use the json file to add additional configuration:
https://github.com/alangrainger/immich-public-proxy?tab=readme-ov-file#additional-configuration

But its not possible to moint single files on QNAP NAS systems and some other environments.
So it's important to change it that we can a folder instead, which will contain the config.json

That would be great!

**Comment by alangrainger** [comment]
I might be misunderstanding, but couldn't you mount a folder however you like, but then reference the `config.json` file inside that folder in the docker-compose file?

**Comment by alangrainger** [comment]
Closing ticket pending on reply from OP.
