### ISSUE TITLE
download-all.svg is downloaded from a different path to other assets

### ISSUE THREAD

**Issue by ESHARK22** [alangrainger/immich-public-proxy#43]
[download-all.svg](https://github.com/alangrainger/immich-public-proxy/blob/main/app/public/images/download-all.svg) is being downloaded from https://immich-demo.note.sx/images/download-all.svg instead of https://immich-demo.note.sx/share/static/images/download-all.svg . 
All other assets are downloaded from the /share/static/ url, so why should download-all.svg be different?

**Comment by alangrainger** [comment]
Thanks that's fixed now.

> Looking further into it, why is /images the same as /share/static/images?

It's to allow `/robots.txt` and `/favicon.ico` to work, for processes that only look for those files in root. It shouldn't have any negative impact.

https://github.com/alangrainger/immich-public-proxy/blob/58090193a99b4b95755d454ead8c0f9ad80da9b4/app/src/index.ts#L28-L29

**Comment by alangrainger** [comment]
Thanks, those other two have been updated.

> Just update the comments :D

It's not for IPP, it's for other processes (browsers, robots, dashboards) which only look for a favicon at root ;)
